export const classesDisponibles = [
    "6ème",
    "5ème",
    "4ème",
    "3ème",
    "2nde A",
    "2nde C",
    "2nde E",
    "2nde TI",
    "1ère A",
    "1ère C",
    "1ère D",
    "1ère E",
    "1ère TI",
    "Terminale A",
    "Terminale C",
    "Terminale D",
    "Terminale E",
    "Terminale TI"
];
